# Generated by Django 4.2 on 2023-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[["0", "Restaurant"], ["1", "Customer"]],
                default="0",
                max_length=100,
                null=True,
            ),
        ),
    ]
